# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01302c6f26bed40d1a0a4cfaa026a6ef7d190f67a0d91481a490b9b1bb496a83d01b4b41a3c592cb441b23ecfe266e911162dc2cc1b2915af49c64767c7c70a9

test:
  secret_key_base: 3ae18b61f808b9b6bb6b99bef3f9d88b4779649dd5aef1daa56f7dfb2c51bcac97aeeeb46593d61374bd4a04cccd337179585ba1c2caee865313a3dc640c7fb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
